const captureWebsite = require('capture-website')
// const path = require('path')
const moment = require('moment')
const { client } = require('../config')

/**
 * Take an screenshot of the bitfinex chart generated by the client app
 * and save it in /static/screenshots/{timestamp}
 *
 * @return {File} chartImg
 */
async function takeScreenshot() {
    try {
        const fileName = `screen_chartBTC-${moment.now()}.png`
        const screenshotsPath = 'static/screenshots/'
        await captureWebsite.file(client.url, `${screenshotsPath + fileName}`, {
            launchOptions: {
                args: ['--no-sandbox', '--disable-setuid-sandbox'],
            },
        })
        return screenshotsPath + fileName
    } catch (err) {
        console.log(err)
    }
}

module.exports = {
    takeScreenshot,
}
